### ISSUE TITLE
add option to fenominal-cli to use exact/fuzzy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/fenominal#76]
@tudorgroza  -- let's make the fuzzy algorithm default and add a flag for ``--exact-matching`` ?

also, we no longer need the kmer file, correct?
```
java -jar fenominal-cli/target/fenominal-cli-0.7.7-SNAPSHOT.jar P -h
Usage: fenominal parse [-hV] [--hp=<hpoJsonPath>] -i=<input> [-k=<kmerFile>]
                       [-o=<output>]
Parse text
  -h, --help               Show this help message and exit.
      --hp=<hpoJsonPath>   path to HP json file
  -i, --input=<input>      path to input file
  -k, --kmer=<kmerFile>    path to kmer file
  -o, --output=<output>    path to output file
  -V, --version            Print version information and e
```

**Comment by tudorgroza** [comment]
Before doing that - should I clean up the deprecated code?

**Comment by pnrobinson** [comment]
@tudorgroza  -- I spent some time today cleaning things up and refactoring, I removed the deprecated code and added documentation. I am going to look at some of the other issues tomorrow.
