### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/fenominal#80]
@tudorgroza 

In TBlatMatchingStrategy we have this
```
Map<String, List<String>> originalTokenIdxs = res.getSecond();
```
but further down we have this
```
int idx = ... 
if (!originalTokenIdxs.get(kmer).contains(idx)) {
                    to_remove_idx.add(idx);
                }
```

Since originalTokenIdxs contains string, it can never contain an integer -- this possibly works in Python but not in Java -- can we check this?

**Comment by tudorgroza** [comment]
Technically - it should work because it's a base type. I've put in a PR just in case.

**Comment by pnrobinson** [comment]
merged, thanks

**Comment by pnrobinson** [comment]
@tudorgroza 
I am trying to understand the code.
WHy do we have this
```
Map<String, List<String>> originalTokenIdxs = new LinkedHashMap<>();
```
and then convert indices to strings rather than just having this
```
Map<String, List<Integer>> originalTokenIdxs = new LinkedHashMap<>();
```

**Comment by tudorgroza** [comment]
To avoid an issue similar to the thing you've mentioned above. If the inner list is of integers, then later on list.remove(idx) has an ambiguous meaning: it can be remove by value or remove by index. Hence, I've converted the objects to String - to ensure they are not removed by index.

**Comment by pnrobinson** [comment]
Thanks, I added a brief comment to this effect for future generations
